### PR TITLE
Add ActiveJob adapter

### PR DESCRIPTION
**Pull request by dixpac**
Implements adapter for ActiveJob inside the gem.

Connected to the discussion here https://github.com/rails/rails/issues/52929

### CODE REVIEW

**Comment by nesquena** [comment]
Thanks, going to merge!

**Comment by nesquena** [comment]
Nevermind I'll leave it here and let you tell me when it's ready for merge. Thanks for working on this!

**Comment by dixpac** [comment]
@nesquena i think this should work. I did setup locally beanstalk and this works.. For me looks like a simplest solution, wdyt?

In rails there are a few tests about active job perform methods, so should I bring in rails/active_job as a test dependency, or you would go with something more lighter, or... :) ?

**Comment by nesquena** [comment]
Looks good! And go ahead and add rails active job as a test dependency. Thanks!

**Comment by dixpac** [comment]
@nathantsoi when you have some time take a look. I've added active_job and active_support as a dependency (I had to upgrade minitest because of that).
Also, I've added basic active job tests, that assert that correct arguments are placed inside the tube

**Comment by nesquena** [comment]
This looks great, I'll merge and release a new version this weekend. Thank you!

**Comment by dixpac** [comment]
@nesquena I know you are busy, this is just a gentle ping ❤️. Let me know do I need to do anything more

**Comment by nesquena** [comment]
Thanks for the ping! Looks good, I've merged and I'll release a new version soon

**Comment by dixpac** [comment]
Great! If any issues arise in the future, let me know I'll try to help. I'm not using backburner in production but I'll give my best

**Comment by morgoth** [comment]
@nesquena @Earlopain I see this was merged, but no new version released.
Do you think this could be released so the Rails adapter removal could proceed?

**Comment by nesquena** [comment]
@morgoth Pushed as version 1.7!

**Pull request merged**
