### PR TITLE
Add switch for environment to CLI

### PR DESCRIPTION
**Pull request by contentfree**
I needed this for an environment where I couldn't specify the environment on the command line (*cough* a Windows service)

### CODE REVIEW

**Comment by contentfree** [comment]
It doesn't provide a default and it doesn't overwrite a value if it's already present.

**Comment by contentfree** [comment]
Rebased to current master and squashed commits to one.

**Comment by contentfree** [comment]
I'm not sure why that Travis build failed. Works for me in Ruby 2.1.4 using the same seed that failed at Travis.

**Comment by nesquena** [comment]
Can you add this to the README somewhere? I've restarted Travis CI build and it worked now

**Comment by contentfree** [comment]
Added a section for the CLI.

**Comment by nesquena** [comment]
Sweet thanks!

**Pull request merged**
