### PR TITLE
Add support for custom serialization formats

### PR DESCRIPTION
**Pull request by eltone**
By supporting configurable serialization and deserialization procs, we can allow users to format job bodies as they wish.
Defaults to JSON for compatibility.

### CODE REVIEW

**Comment by contentfree** [comment]
Thanks. Looks good to me. @nesquena?

**Comment by eltone** [comment]
Hmm, I actually think this needs more work, jobs are enqueued with hash keys as sybols but are read with keys as strings. This is fine for JSON but would not work for binary formats like MessagePack. Will revisit tomorrow with a small change to `Job`.

**Comment by nesquena** [comment]
Agreed, I like where this is going, thanks for adding this. Once you have a chance to run through it and you think it's ready for merge let us know. We can do a preview release

**Comment by nesquena** [comment]
Also when you get a chance, can you add these options to the README with an example of how to override

**Comment by eltone** [comment]
This should now be good to merge.

**Comment by nesquena** [comment]
Looks good to me, thanks @eltone

**Pull request merged**
